services:
  minilm:
    image: embedding_minilm
    ports:
      - "8000:8000"
    volumes:
      - ./src:/minilm/src/
      - ./pyproject.toml:/minilm/pyproject.toml
    working_dir: /minilm
    networks:
      - minilm-net

networks:
  minilm-net:
    driver: bridge
